name: fldc
description: "FlyLAT DataCenter"
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/illustration/
    - assets/logo/